const carDetails=[
    {
    name:"Desire",
    image:"https://img.gaadicdn.com/images/car-images/large/Maruti/Maruti-Swift-Dzire/5832/SILKY-SILVER_565455.jpg",
    rate:"2000",
    type:"one-way",
    vehicleDetails:{
    seat:"4",
    speedLimit:"60Kmph"
    },
    charges:{
    oneWayRate:2000,
    gst:"5%",
    other:0,
    parking:0,
    total:2100
    },
    source:"jamshedpur",
    destination:"Ranchi"
    },
    {
    name:"Honda Amaze",
    image:"https://imgd.aeplcdn.com/1280x720/n/cw/ec/45951/amaze-facelift-exterior-right-front-three-quarter.jpeg?isig=0&q=85",
    rate:"3000",
    type:"one-way",
    vehicleDetails:{
    seat:"5",
    speedLimit:"90Kmph"
    },
    charges:{
    oneWayRate:2500,
    gst:"5%",
    other:0,
    parking:0,
    total:2600
    },
    source:"Ranchi",
    destination:"Jamshedpur"
    },
    {
    name:"Honda City",
    image:"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/m/RT_V_0de84248d2b24c0cb36c1a83cc840fd8.jpg",
    rate:"3300",
    type:"one-way",
    vehicleDetails:{
    seat:"5",
    speedLimit:"90Kmph"
    },
    charges:{
    oneWayRate:3300,
    gst:"5%",
    other:0,
    parking:0,
    total:3400
    },
    source:"Ranchi",
    destination:"Jamshedpur"
    },
    {
    name:"Scorpio",
    image:"https://www.indiacarnews.com/wp-content/uploads/2018/09/Scorpio-black-colour-image.jpg",
    rate:"4500",
    type:"one-way",
    vehicleDetails:{
    seat:"8",
    speedLimit:"80Kmph"
    },
    charges:{
    oneWayRate:4500,
    gst:"5%",
    other:0,
    parking:0,
    total:4600
    },
    source:"Ranchi",
    destination:"Jamshedpur"
    },
    {
    name:"Verna",
    image:"https://www.carblogindia.com/wp-content/uploads/2017/07/new-2017-hyundai-verna-images-3.jpg",
    rate:"3000",
    type:"one-way",
    vehicleDetails:{
    seat:"5",
    speedLimit:"90Kmph"
    },
    charges:{
    oneWayRate:3000,
    gst:"5%",
    other:0,
    parking:0,
    total:3100
    },
    source:"Ranchi",
    destination:"Jamshedpur"
    },
    {
    name:"Kia Seltos",
    image:"https://www.carblogindia.com/wp-content/uploads/2019/08/Kia-Seltos-3-1068x708.jpg",
    rate:"2000",
    type:"one-way",
    vehicleDetails:{
    seat:"4",
    speedLimit:"70Kmph"
    },
    charges:{
    oneWayRate:2000,
    gst:"5%",
    other:0,
    parking:0,
    total:2100
    },
    source:"Ranchi",
    destination:"Jamshedpur"
    }
    ]
    export default carDetails;